### ISSUE TITLE
[FEATURE] Separate .riq file format parser

### ISSUE THREAD

**Issue by minenice55** [RHeavenStudio/Jukebox#1]
Since programs outside of HS are now parsing the .riq file format, a separate freely available "library" for doing this task is warranted. 

- [x] Move the .riq file format parser into own assembly / namespace 
- [x] Implement updater from "v0" riq files to the new version
- [x] Support for bundled RIQs (BRIQ) to package multiple charts in one file + metadata (campaigns...)
- [x] Add proper exception calls if parsing fails (an editor should catch these and perform actions like showing error screens and abort current action taken on file)
- [x] Create a proper API to interface with the parser
- [x] Add proper identifiers for file version and origin (what environment this .riq file originated from, what version of said environment)
- [x] Cue entity updating via functions linked via reflection(?)
- [x] Option to act on "unknown" data similar to the current implementation in HS
- [ ] Options to easily link externally implemented social features to charts (score sharing, player stats..?) using some kind of ID
- [ ] Asynchronous saving / loading of file contents (would we need Burst?)
- [x] Caching of contents (eg. to stream chart audio, operate on embedded images...)
- [ ] File encryption / obfuscation(?, low priority due to HS' already open nature so this feature wouldn't interest us, _program-side writelocking_ would be a good alternative)

**Comment by Starpelly** [comment]
nice name
