### ISSUE TITLE
Access to 'https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/jillejr.newtonsoft.json-for-unity.converters' was denied

### ISSUE THREAD

**Issue by NeEshMenya** [RHeavenStudio/Jukebox#3]
Basically the error in the title appears in "jukebox" package. because of that i cant launch any RIQ and there is no games in creator
![image](https://github.com/RHeavenStudio/Jukebox/assets/62978866/6c56519b-adf6-4539-9285-22acac4ba0ad)

**Comment by minenice55** [comment]
seems like the author of that package changed their name, I'll fix this shortly
